### ISSUE TITLE
Readme inaccuracy

### ISSUE THREAD

**Issue by maccelerated** [ZacharyKhan/Beavus#10]
The readme claims that the app uses Corvallis's API, which is at http://www.corvallistransit.com/rtt/public/utility/file.aspx but the CorvallisBusAPIManager.swift seems to use some other API source. Is that the official API?

**Comment by ZacharyKhan** [comment]
It’s refreshing to see someone who’s done some due diligence. What it’s calling is an API that piggy-backs on CTS API and Google Transit. Data from CTS is merged with data from Google Transit, with some convenient projections applied, and mapped into some easily-digestable JSON. That is why I’m not calling the Corvallis Transit API directly.

**Comment by maccelerated** [comment]
Understood, thank you. It may help to explain where the API is being provided from and who is paying for the server to aid other developers who want to contribute to Beavus.

**Comment by ZacharyKhan** [comment]
I’ll find some time later today and include some info on the API that Beavus is using! Thanks for your input!
